In [1]:
# Create a random 3x4 matric with value between 0-100 and perform this tasks below 
# sort this matrix 
# sort this matrix based n the values in the 2nd col
# sort this matrix based on max value  in each row
# sort based on elements value


In [2]:
import numpy as np

In [3]:
array = np.random.randint(0,100,(3,4))
array

array([[90, 19, 63, 39],
       [41, 19, 59, 90],
       [44, 24, 20, 68]])

In [5]:
array.sort()
array

array([[19, 39, 63, 90],
       [19, 41, 59, 90],
       [20, 24, 44, 68]])

In [9]:
array[:,1].sort()
array

array([[19, 24, 63, 90],
       [19, 39, 59, 90],
       [20, 41, 44, 68]])

In [12]:
array[-1].sort()
array

array([[19, 24, 63, 90],
       [19, 39, 59, 90],
       [20, 41, 44, 68]])

There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.


i. Add marks every student of an extra subject in the same array.

ii. Add two new students marks in respective 5 subjects.(one subject added in above task)

iii. Add extra column with sum of all subjects(5-subjects) marks

iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

In [13]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks

array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [14]:
type(marks)

numpy.ndarray

In [16]:
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1,1)

In [17]:
extra_subject

array([[41],
       [87],
       [72],
       [36],
       [92]])

In [34]:
array = np.concatenate((marks,extra_subject),axis=1)
array

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [39]:
array

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [35]:
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)

In [38]:
print(marks.shape)
print(rec1.shape)

(5, 4)
(1, 5)


In [42]:
array = np.concatenate((array,rec1,rec2),axis=0)

In [44]:
sum = array.sum(axis=1,keepdims=True)
sum

array([[106],
       [328],
       [229],
       [234],
       [315],
       [442],
       [329]])

In [46]:
array = np.concatenate((array,sum),axis=1)
array

array([[ 13,  10,   9,  33,  41, 106, 106],
       [ 63,  46,  90,  42,  87, 328, 328],
       [ 39,  76,  13,  29,  72, 229, 229],
       [ 82,   9,  29,  78,  36, 234, 234],
       [ 67,  61,  59,  36,  92, 315, 315],
       [ 77,  83,  98,  95,  89, 442, 442],
       [ 92,  71,  52,  61,  53, 329, 329]])

In [50]:
# Find unique arrays from a 2d array column wise and row wise 
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [51]:
unique_rows = np.unique(arr, axis=0)
unique_rows

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [52]:
unique_cols = np.unique(arr, axis=1)
unique_cols

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])