In [1]:
import numpy as np

In [3]:
# Create a null vector of size 10 but the fifth value which is 1
a = np.nan * np.ones(10)
a[4] = 1
print(a)

[nan nan nan nan  1. nan nan nan nan nan]


In [6]:
# ask the user to iunput two number a,b. Write a program to generate a random array of shape (a,b) and print the array and the average of the array 
a,b = int(input()),int(input())
list = np.random.random((a,b))
print(list)
print(np.mean(list))

[[0.96270208 0.282466   0.04832191]
 [0.72254282 0.99442804 0.22538062]
 [0.66795358 0.63031433 0.24421086]]
0.5309244695626459


In [12]:
# Write a function to create a 2d array with 1 one the border and 0 inside. Take as input the shape of the array
a = int(input())
b = int(input())
createArray(a,b)
def createArray(a,b):
    x = np.ones((a,b))
    x[1:-1:,1:-1] = 0
    print(x)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
#create a vector of size 10 ranging from 0,1 both excluded
np.linspace(0,1,10)[1:-1]

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [22]:
# create a 3,4 identity matrix
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [25]:
#create a 5x5 matric with rows value ranging from 0,4
z = np.zeros((5,5))
z + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [26]:
''' consider a random integer(in range 1 to 100) vector with shape (10,2) representing coordinates,
and coordinates pf a point as array is given.Create an array of distance of each point in the random vector
from the given point
'''

n = np.random.randint(1,100,(10,2))
point = np.array([50,50])
distance = np.sqrt(np.sum((n-point)**2,axis=1))
print(distance)

[54.12947441 52.35456045 48.09365863 48.33218389 54.58937626 29.
 46.04345773 36.34556369 13.89244399 67.17886572]


In [27]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(100, (6,7,8))

(1, 5, 4)

# Arrays

In [31]:
"""
you re given a space separed list of number. Your task is to print a reversed Numpy array with the element 
type float 
Input Format:

A single line of input containing space separated numbers.

Output Format:

Print the reverse NumPy array with type float.

"""

a = input().split()
a = np.array(a,dtype=float)
print(a[::-1])

[0. 9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [32]:
# Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.
def softmax(x):
    if type(x) != np.ndarray:
        raise ValueError("Input must be a numpy array")
    if x.ndim != 1:
        raise ValueError("Input must be a 1D array")
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

In [33]:
# Vertical stack Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

print(np.vstack((a, b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
'''Create a python function named date_array that accepts two dates as string format and returns a numpy array
of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. 
The date format should be like this only: 2022-12-6. The end date should be included and for simplicity, 
choose dates from a same year.'''

In [ ]:
#substract the mean of each row from a matrix

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = a - a.mean(axis=1,keepdims=True)# keepdims is to keep the dimension
print(a)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [39]:
# swap columns-1 of array with columns 2 in the array 
a = np.arange(9).reshape(3,3)
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [45]:
#replace the odd elements in the array with -1
a[a%2==1] = -1
a

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])