In [1]:
import numpy as np

In [2]:
# Find the nearest element in the array to a given integer
a=23 
array = np.array([10, 17, 24, 31, 38, 45, 52, 59])

index = (np.abs(array - a)).argmin()
print(array[index])


24


In [3]:
# Replace mutiples of 3 or 5 as 0 in the given array 
array

array([10, 17, 24, 31, 38, 45, 52, 59])

In [4]:
array[array % 3 == 0] = 0
array[array % 5 == 0] = 0
print(array)

[ 0 17  0 31 38  0 52 59]


In [ ]:
# Use Fancy indexing
# double the array elements in the given index
array

array([ 0, 17,  0, 31, 38,  0, 52, 59])

In [10]:
arr = np.arange(10)
indexes = [0,3,4,9]

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[indexes] = arr[indexes] * 2
arr

array([ 0,  1,  2,  6,  8,  5,  6,  7,  8, 18])